version: '3.9'
services:
  webpack:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app/balengineering
    ports:
      - '9001:9001'
    command: ["npm", "run", "start"]

  php:
    image: php:fpm
    volumes:
      - ./public:/usr/share/nginx/html

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./public:/usr/src/app/balengineering/public
    ports:
      - '8080:80'
    depends_on:
      - webpack
      - php
    links:
      - php
